x-veld:
  executable:
    about:
      description: "dummy veld for testing and showcasing"
    input:
      path: /veld/input/data.json
      format: "json"
      kind: "dummy data"
    output:
      path: /veld/output/data.xml
      format: "xml"
      kind: "dummy data"

services:
  veld:
    build: .
    volumes:
      - ./convert.py:/veld/executable/convert.py
    command: python /veld/executable/convert.py

